### ISSUE TITLE
Python2 crashes with non-ascii characters.

### ISSUE THREAD

**Issue by thanosgn** [s0md3v/hue#28]
Hi,

When using huepy with python2 I face a problem when the string to be printed includes non-ascii characters.
Python3 works fine though.

Here is a minimal working example that demonstrates this behavior.

```python
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals
from huepy import *

def main():
    pizza = 'John’s Pizza'
    print('Pizza: |' + green(pizza) + '|' )

if __name__ == '__main__':
    main()
```

Python3 execution:
```bash
❯ python3 huepy_unicode_test.py
Pizza: |John’s Pizza|
```

Python2 execution:
```bash
❯ python2 huepy_unicode_test.py 
Traceback (most recent call last):
  File "huepy_unicode_test.py", line 10, in <module>
    main()
  File "huepy_unicode_test.py", line 7, in main
    print('Pizza: |' + green(pizza) + '|' )
  File "/usr/local/lib/python2.7/dist-packages/huepy/__init__.py", line 53, in <lambda>
    locals()[key] = lambda s, prefix=prefix, key=value: _gen(s, prefix, key)
  File "/usr/local/lib/python2.7/dist-packages/huepy/__init__.py", line 47, in _gen
    return '\033[{}m{}\033[0m{}'.format(key, colored, not_colored)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)
```

**Comment by thanosgn** [comment]
I have added a pull request (#29) that addresses this issue.
